-- SQL Server Integration Test DDL

IF OBJECT_ID('TABLE1', 'U') IS NOT NULL DROP TABLE TABLE1;
CREATE TABLE TABLE1 (
    ID INT PRIMARY KEY,
    COLUMN1 NVARCHAR(100) NOT NULL,
    COLUMN2 DATETIME2 DEFAULT SYSDATETIME(),
    -- SQL Server-specific types (CSV-compatible)
    COLUMN3 BIT NOT NULL,
    COLUMN4 DECIMAL(3, 1),
    COLUMN5 NVARCHAR(MAX)
);
