-- Oracle Integration Test DDL

DROP TABLE TABLE1 CASCADE CONSTRAINTS;
CREATE TABLE TABLE1 (
    ID NUMBER(10) PRIMARY KEY,
    COLUMN1 VARCHAR2(100) NOT NULL,
    COLUMN2 TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    -- Oracle-specific types (CSV-compatible)
    COLUMN3 NUMBER(1) NOT NULL,
    COLUMN4 NUMBER(3, 1),
    COLUMN5 VARCHAR2(500)
);
