-- DDL for AnnotationConfigurationTest (H2 Database)

CREATE TABLE TABLE1 (
    ID INTEGER PRIMARY KEY,
    COLUMN1 VARCHAR(100) NOT NULL,
    COLUMN2 VARCHAR(100)
);

CREATE TABLE TABLE2 (
    ID INTEGER PRIMARY KEY,
    COLUMN1 VARCHAR(100) NOT NULL,
    COLUMN2 INTEGER,
    COLUMN3 DECIMAL(10, 2),
    FOREIGN KEY (COLUMN2) REFERENCES TABLE1(ID)
);
