-- DDL for CustomExpectationPathsTest (H2 Database)

CREATE TABLE TABLE1 (
    ID INTEGER PRIMARY KEY,
    COLUMN1 INTEGER NOT NULL,
    COLUMN2 DECIMAL(10, 2) NOT NULL,
    COLUMN3 DATE NOT NULL,
    COLUMN4 VARCHAR(20) NOT NULL
);

CREATE TABLE TABLE2 (
    ID INTEGER PRIMARY KEY,
    COLUMN1 INTEGER NOT NULL,
    COLUMN2 VARCHAR(100) NOT NULL,
    COLUMN3 INTEGER NOT NULL,
    COLUMN4 DECIMAL(10, 2) NOT NULL,
    FOREIGN KEY (COLUMN1) REFERENCES TABLE1(ID)
);
