-- DDL for NestedConventionTest

DROP TABLE IF EXISTS TABLE1;
CREATE TABLE TABLE1 (
    ID INT PRIMARY KEY,
    COLUMN1 VARCHAR(50) NOT NULL,
    COLUMN2 VARCHAR(100) NOT NULL,
    COLUMN3 BOOLEAN NOT NULL
);

DROP TABLE IF EXISTS TABLE2;
CREATE TABLE TABLE2 (
    ID INT PRIMARY KEY,
    COLUMN1 VARCHAR(100) NOT NULL,
    COLUMN2 DECIMAL(10, 2) NOT NULL,
    COLUMN3 INT NOT NULL
);
