-- DDL for NullAndEmptyValuesTest (H2 Database)

CREATE TABLE TABLE1 (
    ID INTEGER PRIMARY KEY,
    COLUMN1 VARCHAR(50) NOT NULL,
    COLUMN2 VARCHAR(50),
    COLUMN3 INTEGER NOT NULL,
    COLUMN4 INTEGER
);
