-- DDL for PartialColumnValidationTest (H2 Database)

CREATE TABLE TABLE1 (
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    COLUMN1 VARCHAR(50) NOT NULL,
    COLUMN2 VARCHAR(50) NOT NULL,
    COLUMN3 INTEGER NOT NULL,
    COLUMN4 TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    COLUMN5 VARCHAR(50) DEFAULT 'SYSTEM'
);
