-- DDL for TableOrderingStrategiesTest (H2 Database)

CREATE TABLE TABLE1 (
    ID INTEGER PRIMARY KEY,
    COLUMN1 VARCHAR(100) NOT NULL
);

CREATE TABLE TABLE2 (
    ID INTEGER PRIMARY KEY,
    COLUMN1 INTEGER NOT NULL,
    COLUMN2 VARCHAR(100) NOT NULL,
    FOREIGN KEY (COLUMN1) REFERENCES TABLE1(ID)
);

CREATE TABLE TABLE3 (
    ID INTEGER PRIMARY KEY,
    COLUMN1 VARCHAR(50) NOT NULL
);

CREATE TABLE TABLE4 (
    COLUMN1 INTEGER NOT NULL,
    COLUMN2 INTEGER NOT NULL,
    PRIMARY KEY (COLUMN1, COLUMN2),
    FOREIGN KEY (COLUMN1) REFERENCES TABLE2(ID),
    FOREIGN KEY (COLUMN2) REFERENCES TABLE3(ID)
);
