-- HSQLDB Integration Test DDL

DROP TABLE IF EXISTS TABLE1;
CREATE TABLE TABLE1 (
    ID INT PRIMARY KEY,
    COLUMN1 VARCHAR(100) NOT NULL,
    COLUMN2 TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    -- HSQLDB standard types
    COLUMN3 BOOLEAN NOT NULL,
    COLUMN4 DECIMAL(3, 1),
    COLUMN5 CLOB,
    COLUMN6 DECIMAL(10, 2)
);
